#!/bin/sh -e

#!/bin/sh

BUILD_TYPE=${BUILD_TYPE:-RelWithDebInfo}
BUILD_DIR="${BUILD_TYPE}"

mkdir -p .web
cd .web

if [ ! -f "${BUILD_DIR}/build.ninja" ]
then
	emcmake cmake \
		-G "Ninja" \
		-B ${BUILD_DIR} \
		-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
		-DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		../
fi

cmake --build ${BUILD_DIR}
