#!/bin/sh -e

export BUILD_TYPE=${BUILD_TYPE:-RelWithDebInfo}

./build-web $@ || true

inotifywait -r -e CLOSE_WRITE -m include src sample | \
	while read path action file
	do
		clear
		./build-web $@ || true
		echo "Done"
	done
